// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgdzV5Xz0oF-Xkez3E6nT68GzaZAI8zdg',
    appId: '1:647627347924:web:cd71eb176dd3dab6042841',
    messagingSenderId: '647627347924',
    projectId: 'quizx-fb763',
    authDomain: 'quizx-fb763.firebaseapp.com',
    storageBucket: 'quizx-fb763.appspot.com',
    measurementId: 'G-GW90EX7F84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHIzxyLdlTQOfIC5QWDGWmzeq77dKaSd8',
    appId: '1:647627347924:android:4486b3a791306744042841',
    messagingSenderId: '647627347924',
    projectId: 'quizx-fb763',
    storageBucket: 'quizx-fb763.appspot.com',
  );
}
